---
apiVersion: v1
kind: Namespace
metadata:
  name: bpf-stuff
---
apiVersion: v1
kind: Service
metadata:
  name: bpf-program
  namespace: bpf-stuff
  labels:
    app: bpf-program
spec:
  ports:
    - port: 8080
      name: metrics
  clusterIP: None
  selector:
    app: bpf-program
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bpf-program
  namespace: bpf-stuff
  labels:
    app: bpf-program
spec:
  selector:
    matchLabels:
      name: bpf-program
  template:
    metadata:
      labels:
        name: bpf-program
    spec:
      containers:
        - name: bpf-program
          image: docker.io/bpftools/prometheus-ebpf-example:latest
          imagePullPolicy: Always
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: URETPROBE_BINARY
              value: /host/usr/bin/bash
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: headers
              mountPath: /usr/src
              readOnly: true
            - name: modules
              mountPath: /lib/modules
              readOnly: true
            - name: bin
              mountPath: /host/usr/bin
              readOnly: true
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: headers
          hostPath:
            path: /usr/src
        - name: modules
          hostPath:
            path: /lib/modules
        - name: bin
          hostPath:
            path: /usr/bin
